### ISSUE TITLE
Neruina refusing to work with several other mods

### ISSUE THREAD

**Issue by 1Mercenary** [Benjamin-Norton/Neruina#17]
Hi!

I'm having some fun creating a medieval modpack, but a run of mine whilst testing it ended with a Ticking Entity crash. I knew I needed this mod, but once it was downloaded, other mods started throwing errors. First Kambrik and then something called 'soundcategories'.

I know it's Neruina, as removing the mod lets the modpack launch again. I'll need to find another fix for now, but I thought I should let you know. I'll attach both logs.

Let me know if you need more information. If I forget about this thread and don't message back, my discord is 0Mercenary.

[latest.log](https://github.com/Bawnorton/Neruina/files/12789331/latest.log)
[2023-10-03-7.log](https://github.com/Bawnorton/Neruina/files/12789337/2023-10-03-7.log)

**Comment by Bawnorton** [comment]
Issue is not with Neruina despite it seeming to be.

The issue is neruina ships a more up to date version of a library that many modders use, this library will always use the most up to date version and MemoryLeakFix uses it's internals (bad idea) which change from version to version, thus, breaking when introduced to a newer version of the library. 

Update or remove MemoryLeakFix and this issue will be resolved.

Don't blame you for thinking it's from neruina as the crash logs won't properly display the cause to the end user but if you look closer you can find the cause.

![image](https://github.com/Bawnorton/Neruina/assets/18416784/6120c8d7-901b-43b1-a5ca-8fba2360d935)

**Comment by 1Mercenary** [comment]
I'll give it a go, thank you ^^
