### ISSUE TITLE
Random Crashes

### ISSUE THREAD

**Issue by WonderlandRose** [Benjamin-Norton/Neruina#32]
Hi, I was playing the modpack Bigchadguys plus, and was having crashes and got told to turn here as they couldnt figure out why I was crashing. Here are my logs and hopefully it can be figured out ^^
[2024-01-04-1.log.gz](https://github.com/Bawnorton/Neruina/files/13837565/2024-01-04-1.log.gz)
[latest.log](https://github.com/Bawnorton/Neruina/files/13837566/latest.log)

**Comment by Bawnorton** [comment]
Neruina doesn't appear to be the cause as the ticking exception was handled, do you have a crash report?

**Comment by WonderlandRose** [comment]
I do not from what I know

**Comment by Bawnorton** [comment]
it'll be located at `.minecraft/crash-reports/`

**Comment by WonderlandRose** [comment]
I do not. I use ATLauncher and dont see one in either the launcher itself or a craft-report folder in the minecraft folder itself

**Comment by Bawnorton** [comment]
Can you consistently make the crash happen or is it sporadic?

**Comment by WonderlandRose** [comment]
It just happens randomly while I am playing and I dont see any pattern. Im normally just exploring and it crashes

**Comment by Bawnorton** [comment]
No crash in the log and no crash report 🤔, makes debugging neigh impossible without resorting to removing mods, and since it's not consistent that's not viable either. 
I highly doubt Neruina causes this but you can disable Neruina's exception handling in the config located at `.minecraft/configs/neruina.json` and set the handling options to false. 
Other than that all I can recommend is trying to identify a pattern in the crashes
