### ISSUE TITLE
Intense Chat Spam

### ISSUE THREAD

**Issue by s0res** [Benjamin-Norton/Neruina#6]
Hey,

Im playing MineColonies: Dimensional Adventure on my g-portal Server. Since i built the Minecolony tavern is get an error message EVERY night for EVERY colonist, it states that an ticking entity has been found and killed, but in fact, no one gets ever killed. I dont get it, any way to resolve this ?

Neruina v1.1.1
Minecolonies v1.20.1-1.1.28

best regards
Stefan
![Screenshot 2023-07-25 112137](https://github.com/Benjamin-Norton/Neruina/assets/89044525/70301795-d0e2-4913-a952-a1580c723a54)

**Comment by Bawnorton** [comment]
Check your logs for the cause. Neruina is simply stopping your game from crashing, there is definitely an underlying problem that will need to be addressed. I expect the structure is spawning new entities that are immediately killed as they would otherwise cause the game to crash. Neruina kills entities in a way such that they continue to "safe tick" to allow the drops to happen, but are essentially removed rather than dealing damage to them, thus, you won't see the entity for more than 1 render tick (1 frame), there will be no death animation.
